[project]
name = "crosswalk-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyzmq>=26.4.0",
    "zmq>=0.0.0",
    "pydantic>=2.0.0",
    "gpiozero>=2.0.1",
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
]
