---
crosswalk_led_angle: 90
crosswalk_button_pin: 19
crosswalk_interaction: tcp://crosswalk-a.local:5556
crosswalk_controller: tcp://crosswalk-a.local:5557
crosswalk_heartbeat: tcp://crosswalk-a.local:5558
crosswalk_hostname: crosswalk-b
crosswalk_services:
  - xwalk_audio_player
  - xwalk_button_light
  - xwalk_button_switch
  - xwalk_matrix_driver
  - xwalk_sys_control
