---
- name: Restart NetworkManager
  systemd:
    name: NetworkManager
    state: restarted

- name: Restart chrony
  systemd:
    name: chrony
    state: restarted

- name: Reboot pi
  become: yes
  ansible.builtin.reboot:
    reboot_timeout: 300
