---
- import_tasks: initial.yml
  tags:
    -initial

- import_tasks: code.yml
  tags:
    - code

- import_tasks: sound.yml
  tags:
    - sound
    
- import_tasks: ap.yml
  tags:
    - ap

- import_tasks: wifi.yml
  tags:
    - wifi