---
- name: Quiet hours entry cron
  cron:
    name: "start quiet hours"
    hour: '2-8'
    minute: '*/10'
    job: 'amixer -c Device set Speaker 50\%'

- name: Quiet hours exit cron
  cron:
    name: "stop quiet hours"
    hour: '9-22'
    minute: '*/10'
    job: 'amixer -c Device set Speaker 90\%'
